set(BETTERSPRAY_DEPENDENCY_CACHE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/cache" CACHE PATH "Downloaded binary dependency cache")
set(VC_LTL_Root "$ENV{VC_LTL_Root}" CACHE PATH "Existing VC-LTL binary package; empty downloads the verified package")
foreach(dependency METAHOOK VGUI2EXTENSION UTILTHREADTASK UTILHTTPCLIENT STEAMSDK FREEIMAGE LIBXML2 SCOPEEXIT CHOCOBO1HASH)
    set(${dependency}_SOURCE_PATH "$ENV{${dependency}_SOURCE_PATH}" CACHE PATH "${dependency} source tree; empty fetches the pinned version")
endforeach()

function(betterspray_require_files name source)
    foreach(required IN LISTS ARGN)
        if(NOT EXISTS "${source}/${required}" OR IS_DIRECTORY "${source}/${required}")
            message(FATAL_ERROR "${name} is missing ${required}: ${source}")
        endif()
    endforeach()
endfunction()

function(betterspray_fetch_source name url commit out_var)
    include(FetchContent)
    FetchContent_Declare(${name}
        GIT_REPOSITORY "${url}" GIT_TAG "${commit}"
        GIT_SUBMODULES "" GIT_SUBMODULES_RECURSE FALSE
        # Populate only: dependency projects are configured separately below.
        SOURCE_SUBDIR _betterspray_source_only)
    FetchContent_MakeAvailable(${name})
    set(${out_var} "${${name}_SOURCE_DIR}" PARENT_SCOPE)
endfunction()

function(betterspray_prepare_dependencies)
    set(METAHOOK_files include/metahook.h include/HLSDK/common/interface.cpp include/SourceSDK/filesystem.cpp include/vgui_controls/Panel.cpp LICENSE)
    set(VGUI2EXTENSION_files include/Interface/IVGUI2Extension.h include/Interface/IDpiManager.h
        include/Interface/VGUI/IInput2.h include/Interface/VGUI/IScheme2.h include/Interface/VGUI/ISurface2.h)
    set(UTILTHREADTASK_files include/Interface/IUtilThreadTask.h)
    set(UTILHTTPCLIENT_files include/Interface/IUtilHTTPClient.h)
    set(STEAMSDK_files steam/steam_api.h STEAM-SDK-NOTICE.md)
    set(FREEIMAGE_files CMakeLists.txt Source/FreeImage.h license-fi.txt)
    set(LIBXML2_files CMakeLists.txt include/libxml/parser.h Copyright)
    set(SCOPEEXIT_files include/ScopeExit/ScopeExit.h LICENSE)
    set(CHOCOBO1HASH_files src/md5.h LICENSE)
    set(vcltl_files "VC-LTL helper for cmake.cmake" config/config.cmake Readme.md
        TargetPlatform/6.0.6000.0/lib/Win32/libucrt.lib)
    set(dependencies METAHOOK VGUI2EXTENSION UTILTHREADTASK UTILHTTPCLIENT STEAMSDK FREEIMAGE LIBXML2 SCOPEEXIT CHOCOBO1HASH)

    # Reject invalid explicit paths before downloading anything. Never edit them.
    foreach(dependency IN LISTS dependencies)
        if(${dependency}_SOURCE_PATH)
            get_filename_component(${dependency}_SOURCE_PATH "${${dependency}_SOURCE_PATH}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
            betterspray_require_files("${dependency}_SOURCE_PATH" "${${dependency}_SOURCE_PATH}" ${${dependency}_files})
        endif()
    endforeach()
    if(VC_LTL_Root)
        get_filename_component(VC_LTL_Root "${VC_LTL_Root}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
        betterspray_require_files(VC_LTL_Root "${VC_LTL_Root}" ${vcltl_files})
    endif()

    set(METAHOOK_url https://github.com/MetaHookSv/MetaHook)
    set(METAHOOK_commit 1d23fe946e6f0f09a1a892aa2156c3b462774026)
    set(VGUI2EXTENSION_url https://github.com/MetaHookSv/VGUI2Extension)
    set(VGUI2EXTENSION_commit 07933adf727f8a9a5443d4591d4c1be23b1b9edf)
    set(UTILTHREADTASK_url https://github.com/MetaHookSv/UtilThreadTask)
    set(UTILTHREADTASK_commit 8d36bef696f95b4932cd2d58d50dd8793567dda8)
    set(UTILHTTPCLIENT_url https://github.com/MetaHookSv/UtilHTTPClient_libcurl)
    set(UTILHTTPCLIENT_commit 0bc8f39eb178c9c125a58efd3e3e73bd75fc3e15)
    set(STEAMSDK_url https://github.com/MetaHookSv/SteamSDK)
    set(STEAMSDK_commit 3c1abaf6277f9f99fd16ef40557d6852820b848f)
    set(FREEIMAGE_url https://github.com/hzqst/FreeImage_clone)
    set(FREEIMAGE_commit c68700b9fe699dbbf99f88a611065f101cba1a41)
    set(LIBXML2_url https://github.com/GNOME/libxml2)
    set(LIBXML2_commit 718a140a367cb89192587d3dc80bf389f5aca531)
    set(SCOPEEXIT_url https://github.com/SergiusTheBest/ScopeExit)
    set(SCOPEEXIT_commit bd345da594a4675d04de663d93d00cb81b6678b2)
    set(CHOCOBO1HASH_url https://github.com/hzqst/Chocobo1Hash)
    set(CHOCOBO1HASH_commit f455b0e350dce4c3b2415bad5f10484842b0a605)
    foreach(dependency IN LISTS dependencies)
        if(NOT ${dependency}_SOURCE_PATH)
            string(TOLOWER "${dependency}" name)
            betterspray_fetch_source(betterspray_${name} "${${dependency}_url}" "${${dependency}_commit}" ${dependency}_SOURCE_PATH)
        endif()
        betterspray_require_files("${dependency}_SOURCE_PATH" "${${dependency}_SOURCE_PATH}" ${${dependency}_files})
        set(${dependency}_SOURCE_PATH "${${dependency}_SOURCE_PATH}" PARENT_SCOPE)
        message(STATUS "${dependency}_SOURCE_PATH: ${${dependency}_SOURCE_PATH}")
    endforeach()

    if(NOT VC_LTL_Root)
        set(VC_LTL_Root "${BETTERSPRAY_DEPENDENCY_CACHE_DIR}/VC-LTL-5.3.1")
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VCLTL.cmake")
        betterspray_prepare_vcltl()
    endif()
    betterspray_require_files(VC_LTL_Root "${VC_LTL_Root}" ${vcltl_files})
    set(VC_LTL_Root "${VC_LTL_Root}" PARENT_SCOPE)
    message(STATUS "VC_LTL_Root: ${VC_LTL_Root}")

endfunction()
