add_executable(BetterSprayGameDataResolverTests tests/gamedata_resolver_tests.cpp src/privatehook.cpp)
target_link_libraries(BetterSprayGameDataResolverTests PRIVATE betterspray_settings)
add_executable(BetterSprayImageLibraryTests tests/image_library_tests.cpp)
target_link_libraries(BetterSprayImageLibraryTests PRIVATE FreeImage LibXml2::LibXml2)
add_custom_command(TARGET BetterSprayImageLibraryTests POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "$<TARGET_FILE:FreeImage>" "$<TARGET_FILE:LibXml2>" "$<TARGET_FILE_DIR:BetterSprayImageLibraryTests>"
    VERBATIM)
add_executable(BetterSprayPluginLoadSmoke tests/plugin_load_smoke.cpp)
target_link_libraries(BetterSprayPluginLoadSmoke PRIVATE betterspray_settings)
add_dependencies(BetterSprayPluginLoadSmoke BetterSpray)
foreach(test BetterSprayGameDataResolverTests BetterSprayImageLibraryTests BetterSprayPluginLoadSmoke)
    target_compile_features(${test} PRIVATE cxx_std_20)
    target_compile_options(${test} PRIVATE /W4 /WX /UNDEBUG)
    set_target_properties(${test} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/tests")
endforeach()
foreach(scenario success first_missing missing kind_mismatch catalog_conflict null_address error_returns)
    add_test(NAME betterspray_gamedata_${scenario} COMMAND BetterSprayGameDataResolverTests ${scenario})
endforeach()
foreach(scenario PNG WEBP HTML)
    add_test(NAME betterspray_library_${scenario} COMMAND BetterSprayImageLibraryTests ${scenario})
endforeach()
add_test(NAME betterspray_plugin_factory COMMAND BetterSprayPluginLoadSmoke "$<TARGET_FILE:BetterSpray>"
    "$<TARGET_FILE:FreeImage>" "$<TARGET_FILE:LibXml2>" "$<TARGET_FILE:SteamAPIBridge>")
get_property(betterspray_tests DIRECTORY PROPERTY TESTS)
set_tests_properties(${betterspray_tests} PROPERTIES TIMEOUT 30)
