add_executable(GameDataResolverTests tests/gamedata_resolver_tests.cpp src/privatehook.cpp)
target_link_libraries(GameDataResolverTests PRIVATE betterspray_settings)
add_executable(ImageLibraryTests tests/image_library_tests.cpp)
target_link_libraries(ImageLibraryTests PRIVATE FreeImage LibXml2::LibXml2)
add_custom_command(TARGET ImageLibraryTests POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "$<TARGET_FILE:FreeImage>" "$<TARGET_FILE:LibXml2>" "$<TARGET_FILE_DIR:ImageLibraryTests>"
    VERBATIM)
add_executable(PluginLoadSmoke tests/plugin_load_smoke.cpp)
target_link_libraries(PluginLoadSmoke PRIVATE betterspray_settings)
add_dependencies(PluginLoadSmoke BetterSpray)
foreach(test GameDataResolverTests ImageLibraryTests PluginLoadSmoke)
    target_compile_features(${test} PRIVATE cxx_std_20)
    target_compile_options(${test} PRIVATE /W4 /WX /UNDEBUG)
    set_target_properties(${test} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tests")
endforeach()
foreach(scenario success first_missing missing kind_mismatch catalog_conflict null_address error_returns)
    add_test(NAME gamedata_${scenario} COMMAND GameDataResolverTests ${scenario})
endforeach()
foreach(scenario PNG WEBP HTML)
    add_test(NAME library_${scenario} COMMAND ImageLibraryTests ${scenario})
endforeach()
add_test(NAME plugin_factory COMMAND PluginLoadSmoke "$<TARGET_FILE:BetterSpray>"
    "$<TARGET_FILE:FreeImage>" "$<TARGET_FILE:LibXml2>" "${STEAMSDK_SOURCE_PATH}/bin/steam_api.dll")
get_property(betterspray_tests DIRECTORY PROPERTY TESTS)
set_tests_properties(${betterspray_tests} PROPERTIES TIMEOUT 30)
